### ISSUE TITLE
/auth/login response

### ISSUE THREAD

**Issue by Seth10001** [GatorloopSoftwareTeam/gatorloop-backend#10]
Currently the `/auth/login` route returns HTML after POST request is performed. It should return JSON as the rest of the routes do.

**Comment by Seth10001** [comment]
ex.
After a successful login: 
`<p>Hello, Admin User. View your <a href="/profile">profile</a>.</p>`

**Comment by NoahTK7** [comment]
fixed with the following commit to master branch https://github.com/GatorloopSoftwareTeam/gatorloop-backend/commit/f72a94ca4eab9fbf50d6460df60d5e82ba420ef1
